
version: "2.1"
services:
  https-portal-www:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    links:
      - slack_listener
    environment:
      DOMAINS: 'www.${PUBLIC_DOMAIN}, ${PUBLIC_DOMAIN}->http://slack_listener:9090'
      PRODUCTION: 'true'
    volumes:
        - /data/https-portal/vhosts:/var/www/vhosts
        - /data/ssl_certs:/var/lib/https-portal   

  queuem:
    image: rabbitmq:3
    #image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - '5671:5671'
##      - '5672:5672' #(TCP non-SSL )
##      - '15672:15672' #(HTTP)
      - '15671:15671'    
#    environment:
##     - RABBITMQ_DEFAULT_USER=${QUEUE_USER}
##      - RABBITMQ_DEFAULT_PASS=${QUEUE_PASSWORD}
#      - RABBITMQ_SSL_CACERTFILE=/certs/ca_certificate.pem
#      - RABBITMQ_SSL_CERTFILE=/certs/server_certificate.pem
#      - RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=true
#      - RABBITMQ_SSL_KEYFILE=/certs/server_key.pem
#      - RABBITMQ_SSL_VERIFY=verify_peer
#    volumes:
#        - certsvol:/certs

  slack_listener:
    image: slack_listener
    environment:
      - BOT_USER_ID
      - QUEUE_HOSTNAME
      - QUEUE_USER
      - QUEUE_PASSWORD      
      - OUT_QUEUE=input
    restart: always
    links:
      - queuem:queuem

  slack_writer:
    image: slack_writer
    environment:
      - BOT_USER_ID
      - SLACK_TOKEN
      - QUEUE_HOSTNAME
      - QUEUE_USER
      - QUEUE_PASSWORD
      - IN_QUEUE=input      
    restart: always
    links:
      - queuem:queuem

#volumes:
#  certsvol:
#    external:
#      name: rabbit-certs
